# Generated by protolark. Do not edit.
"""Schema-generated protobuf configuration constructors."""

load("@protolark//protolark:runtime.bzl", _protolark_create = "create_message")

def _protolark_type_0_create(**kwargs):
    return _protolark_create(
        "example.Owner",
        {
            "name": ("string", False, False, "", [], "", "", []),
        },
        kwargs,
    )

def _protolark_type_1_create(**kwargs):
    return _protolark_create(
        "example.Project",
        {
            "enabled": ("bool", False, False, "_enabled", [], "", "", []),
            "labels": ("message", True, False, "", [], "string", "string", []),
            "local_path": ("string", False, False, "location", [], "", "", []),
            "mode": ("enum", False, False, "", [0, 1], "", "", []),
            "name": ("string", False, False, "", [], "", "", []),
            "owner": ("message", False, False, "", [], "", "", []),
            "remote_url": ("string", False, False, "location", [], "", "", []),
            "settings": ("message", False, False, "", [], "", "", []),
            "targets": ("string", True, False, "", [], "", "", []),
        },
        kwargs,
    )

def _protolark_type_4_create(**kwargs):
    return _protolark_create(
        "example.Project.Settings",
        {
            "timeout_seconds": ("int32", False, False, "", [], "", "", []),
        },
        kwargs,
    )

_protolark_type_3 = struct(**{
    "FAST": 1,
    "MODE_UNSPECIFIED": 0,
})

_protolark_type_4 = struct(**{
    "create": _protolark_type_4_create,
})

_protolark_type_0 = struct(**{
    "create": _protolark_type_0_create,
})

_protolark_type_1 = struct(**{
    "Mode": _protolark_type_3,
    "Settings": _protolark_type_4,
    "create": _protolark_type_1_create,
})

common_pb2 = struct(**{
    "Owner": _protolark_type_0,
})

project_pb2 = struct(**{
    "Project": _protolark_type_1,
})
