use anyhow::{Context, Result, bail, ensure};
use prost_types::{
    DescriptorProto, EnumDescriptorProto, FieldDescriptorProto, FileDescriptorProto,
    FileDescriptorSet,
    field_descriptor_proto::{Label, Type},
};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

#[derive(Clone, Copy)]
enum Symbol<'a> {
    Message(&'a DescriptorProto),
    Enum(&'a EnumDescriptorProto),
}

/// Generate constructors for selected files and their transitive imports.
/// An empty selection includes all files. Loads the shared Protolark runtime.
pub fn generate(set: &FileDescriptorSet, files: &[String]) -> Result<String> {
    generate_with_runtime(set, files, crate::runtime::SCL_RUNTIME_LABEL)
}

/// Generate constructors with an explicit shared-runtime load label.
pub fn generate_with_runtime(
    set: &FileDescriptorSet,
    files: &[String],
    runtime_load: &str,
) -> Result<String> {
    ensure!(
        !runtime_load.is_empty(),
        "runtime load label must not be empty"
    );
    let mut by_name = BTreeMap::new();
    for file in &set.file {
        let name = file
            .name
            .as_deref()
            .context("descriptor file has no name")?;
        ensure!(!name.is_empty(), "descriptor file has empty name");
        ensure!(
            by_name.insert(name, file).is_none(),
            "duplicate file {name}"
        );
    }
    let mut selected = BTreeSet::new();
    let mut pending: Vec<&str> = if files.is_empty() {
        by_name.keys().copied().collect()
    } else {
        files.iter().map(String::as_str).collect()
    };
    while let Some(name) = pending.pop() {
        let file = by_name.get(name).with_context(|| {
            format!("missing descriptor for {name}; include imports in descriptor set")
        })?;
        if selected.insert(name) {
            pending.extend(file.dependency.iter().map(String::as_str));
        }
    }
    let mut symbols = BTreeMap::new();
    let mut exports = BTreeSet::new();
    for name in &selected {
        let file = by_name[name];
        ensure!(
            matches!(
                file.syntax.as_deref(),
                None | Some("") | Some("proto2") | Some("proto3")
            ),
            "unsupported syntax in {name}"
        );
        ensure!(
            file.extension.is_empty(),
            "extensions are not supported: {name}"
        );
        let export = export_name(name)?;
        ensure!(
            exports.insert(export.clone()),
            "ambiguous file export {export}"
        );
        let prefix = file.package.as_deref().unwrap_or("");
        if !prefix.is_empty() {
            for part in prefix.split('.') {
                identifier(part)?;
            }
        }
        collect(&file.message_type, &file.enum_type, prefix, &mut symbols)?;
    }
    let mut out = format!(
        "# Generated by protolark. Do not edit.\n\"\"\"Schema-generated protobuf configuration constructors.\"\"\"\n\nload({}, _protolark_create = \"create_message\")\n",
        quote(runtime_load)
    );
    let mut ids = BTreeMap::new();
    for (idx, name) in symbols.keys().enumerate() {
        ids.insert(name.clone(), format!("_protolark_type_{idx}"));
    }
    // Factories use scalar descriptors only, so recursive message schemas need no recursion.
    for (name, symbol) in &symbols {
        if let Symbol::Message(message) = symbol {
            if message
                .options
                .as_ref()
                .and_then(|o| o.map_entry)
                .unwrap_or(false)
            {
                continue;
            }
            let specs = field_specs(message, name, &symbols)?;
            writeln!(
                out,
                "\ndef {}_create(**kwargs):\n    return _protolark_create(\n        {},\n        {},\n        kwargs,\n    )",
                ids[name],
                quote(name),
                specs
            )?;
        }
    }
    // Deepest namespaces first: parents can reference nested types without forward references.
    let mut names: Vec<_> = symbols.keys().collect();
    names.sort_by(|a, b| {
        b.matches('.')
            .count()
            .cmp(&a.matches('.').count())
            .then(a.cmp(b))
    });
    for name in names {
        let id = &ids[name];
        let members = match symbols[name] {
            Symbol::Enum(e) => {
                ensure!(!e.value.is_empty(), "enum {name} has no values");
                let mut members = BTreeMap::new();
                for v in &e.value {
                    let key = checked_name(v.name.as_deref(), "enum value")?;
                    let number = v.number.context("enum value has no number")?;
                    ensure!(
                        members.insert(key.to_owned(), number.to_string()).is_none(),
                        "duplicate enum value {name}.{key}"
                    );
                }
                members
            }
            Symbol::Message(m) => {
                if m.options
                    .as_ref()
                    .and_then(|o| o.map_entry)
                    .unwrap_or(false)
                {
                    continue;
                }
                let mut members = BTreeMap::from([("create".to_owned(), format!("{id}_create"))]);
                for nested in &m.nested_type {
                    if nested
                        .options
                        .as_ref()
                        .and_then(|o| o.map_entry)
                        .unwrap_or(false)
                    {
                        continue;
                    }
                    namespace_member(&mut members, nested.name.as_deref(), name, &ids)?;
                }
                for nested in &m.enum_type {
                    namespace_member(&mut members, nested.name.as_deref(), name, &ids)?;
                }
                members
            }
        };
        writeln!(out, "\n{id} = struct(**{})", render_members(&members, 0))?;
    }
    for name in selected {
        let file: &FileDescriptorProto = by_name[name];
        let mut members = BTreeMap::new();
        let prefix = file.package.as_deref().unwrap_or("");
        for m in &file.message_type {
            ensure!(
                !m.options
                    .as_ref()
                    .and_then(|o| o.map_entry)
                    .unwrap_or(false),
                "top-level map entry is invalid"
            );
            namespace_member(&mut members, m.name.as_deref(), prefix, &ids)?;
        }
        for e in &file.enum_type {
            namespace_member(&mut members, e.name.as_deref(), prefix, &ids)?;
        }
        writeln!(
            out,
            "\n{} = struct(**{})",
            export_name(name)?,
            render_members(&members, 0)
        )?;
    }
    Ok(out)
}

fn identifier(s: &str) -> Result<()> {
    let mut chars = s.chars();
    ensure!(
        chars
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
            && chars.all(|c| c.is_ascii_alphanumeric() || c == '_'),
        "invalid protobuf identifier {s:?}"
    );
    Ok(())
}
fn checked_name<'a>(s: Option<&'a str>, kind: &str) -> Result<&'a str> {
    let s = s.with_context(|| format!("{kind} has no name"))?;
    identifier(s)?;
    Ok(s)
}
fn full_name(prefix: &str, name: &str) -> String {
    if prefix.is_empty() {
        name.to_owned()
    } else {
        format!("{prefix}.{name}")
    }
}
fn export_name(path: &str) -> Result<String> {
    let basename = path.rsplit('/').next().context("empty file path")?;
    let stem = basename
        .strip_suffix(".proto")
        .context("descriptor filenames must end in .proto")?;
    identifier(stem)?;
    ensure!(
        !stem.starts_with('_'),
        "file basename cannot begin with underscore: {path}"
    );
    Ok(format!("{stem}_proto"))
}
fn quote(s: &str) -> String {
    format!("{s:?}")
}
fn collect<'a>(
    messages: &'a [DescriptorProto],
    enums: &'a [EnumDescriptorProto],
    prefix: &str,
    symbols: &mut BTreeMap<String, Symbol<'a>>,
) -> Result<()> {
    for message in messages {
        let name = full_name(prefix, checked_name(message.name.as_deref(), "message")?);
        ensure!(
            message.extension.is_empty() && message.extension_range.is_empty(),
            "extensions are not supported: {name}"
        );
        ensure!(
            symbols
                .insert(name.clone(), Symbol::Message(message))
                .is_none(),
            "duplicate type {name}"
        );
        collect(&message.nested_type, &message.enum_type, &name, symbols)?;
    }
    for e in enums {
        let name = full_name(prefix, checked_name(e.name.as_deref(), "enum")?);
        ensure!(
            symbols.insert(name.clone(), Symbol::Enum(e)).is_none(),
            "duplicate type {name}"
        );
    }
    Ok(())
}
fn namespace_member(
    members: &mut BTreeMap<String, String>,
    child: Option<&str>,
    prefix: &str,
    ids: &BTreeMap<String, String>,
) -> Result<()> {
    let child = checked_name(child, "type")?;
    let full = full_name(prefix, child);
    let id = ids
        .get(&full)
        .with_context(|| format!("missing type {full}"))?;
    ensure!(
        members.insert(child.to_owned(), id.clone()).is_none(),
        "namespace collision {full}"
    );
    Ok(())
}
fn render_members(members: &BTreeMap<String, String>, indent: usize) -> String {
    if members.is_empty() {
        return "{}".to_owned();
    }
    let padding = " ".repeat(indent);
    format!(
        "{{\n{}\n{padding}}}",
        members
            .iter()
            .map(|(key, value)| format!("{padding}    {}: {value},", quote(key)))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

fn kind(
    field: &FieldDescriptorProto,
    symbols: &BTreeMap<String, Symbol<'_>>,
) -> Result<(String, String, Option<String>)> {
    let ty =
        Type::try_from(field.r#type.context("field has no type")?).context("invalid field type")?;
    let scalar = match ty {
        Type::Double => "double",
        Type::Float => "float",
        Type::Int64 => "int64",
        Type::Uint64 => "uint64",
        Type::Int32 => "int32",
        Type::Fixed64 => "fixed64",
        Type::Fixed32 => "fixed32",
        Type::Bool => "bool",
        Type::String => "string",
        Type::Bytes => "bytes",
        Type::Uint32 => "uint32",
        Type::Sfixed32 => "sfixed32",
        Type::Sfixed64 => "sfixed64",
        Type::Sint32 => "sint32",
        Type::Sint64 => "sint64",
        Type::Group => bail!("groups are not supported"),
        Type::Message | Type::Enum => {
            let name = field
                .type_name
                .as_deref()
                .context("message/enum field missing type_name")?;
            ensure!(
                name.starts_with('.'),
                "type_name must be fully qualified: {name}"
            );
            let symbol = symbols
                .get(&name[1..])
                .with_context(|| format!("unresolved type {name}"))?;
            return match (ty, symbol) {
                (Type::Message, Symbol::Message(m)) => Ok((
                    "message".into(),
                    "[]".into(),
                    m.options
                        .as_ref()
                        .and_then(|o| o.map_entry)
                        .unwrap_or(false)
                        .then(|| name[1..].to_owned()),
                )),
                (Type::Enum, Symbol::Enum(e)) => {
                    let values: BTreeSet<_> = e
                        .value
                        .iter()
                        .map(|v| v.number.context("enum value missing number"))
                        .collect::<Result<_>>()?;
                    Ok((
                        "enum".into(),
                        format!("{:?}", values.into_iter().collect::<Vec<_>>()),
                        None,
                    ))
                }
                _ => bail!("type kind mismatch for {name}"),
            };
        }
    };
    Ok((scalar.into(), "[]".into(), None))
}
fn field_specs(
    message: &DescriptorProto,
    name: &str,
    symbols: &BTreeMap<String, Symbol<'_>>,
) -> Result<String> {
    let mut specs = BTreeMap::new();
    let mut numbers = BTreeSet::new();
    let mut oneofs = BTreeSet::new();
    for oneof in &message.oneof_decl {
        ensure!(
            oneofs.insert(checked_name(oneof.name.as_deref(), "oneof")?),
            "duplicate oneof in {name}"
        );
    }
    for f in &message.field {
        let field = checked_name(f.name.as_deref(), "field")?;
        let number = f.number.context("field has no number")?;
        ensure!(
            (1..=536870911).contains(&number)
                && !(19000..=19999).contains(&number)
                && numbers.insert(number),
            "invalid/duplicate field number in {name}.{field}"
        );
        let label = Label::try_from(f.label.context("field has no label")?)
            .context("invalid field label")?;
        let (kind_name, allowed, map) =
            kind(f, symbols).with_context(|| format!("{name}.{field}"))?;
        let oneof = if let Some(idx) = f.oneof_index {
            ensure!(
                label == Label::Optional,
                "oneof field must be optional: {name}.{field}"
            );
            let decl = usize::try_from(idx)
                .ok()
                .and_then(|i| message.oneof_decl.get(i))
                .context("invalid oneof index")?;
            checked_name(decl.name.as_deref(), "oneof")?
        } else {
            ""
        };
        let (map_key, map_value, map_allowed) = if let Some(map) = map {
            ensure!(
                label == Label::Repeated,
                "map field must be repeated: {name}.{field}"
            );
            let Some(Symbol::Message(entry)) = symbols.get(&map) else {
                bail!("invalid map entry")
            };
            ensure!(entry.field.len() == 2, "map entry must have key and value");
            let key = entry
                .field
                .iter()
                .find(|f| f.number == Some(1))
                .context("map entry missing key")?;
            let value = entry
                .field
                .iter()
                .find(|f| f.number == Some(2))
                .context("map entry missing value")?;
            ensure!(
                key.name.as_deref() == Some("key")
                    && value.name.as_deref() == Some("value")
                    && key.label == Some(Label::Optional as i32)
                    && value.label == Some(Label::Optional as i32),
                "malformed map entry {map}"
            );
            let (k, _, nested_key) = kind(key, symbols)?;
            ensure!(
                matches!(
                    k.as_str(),
                    "string"
                        | "bool"
                        | "int32"
                        | "int64"
                        | "uint32"
                        | "uint64"
                        | "sint32"
                        | "sint64"
                        | "fixed32"
                        | "fixed64"
                        | "sfixed32"
                        | "sfixed64"
                ) && nested_key.is_none(),
                "invalid map key"
            );
            let (v, a, nested) = kind(value, symbols)?;
            ensure!(nested.is_none(), "map values cannot be map entries");
            (k, v, a)
        } else {
            (String::new(), String::new(), "[]".into())
        };
        let spec = format!(
            "({}, {}, {}, {}, {}, {}, {}, {})",
            quote(&kind_name),
            if label == Label::Repeated {
                "True"
            } else {
                "False"
            },
            if label == Label::Required {
                "True"
            } else {
                "False"
            },
            quote(oneof),
            allowed,
            quote(&map_key),
            quote(&map_value),
            map_allowed
        );
        ensure!(
            specs.insert(field.to_owned(), spec).is_none(),
            "duplicate field {name}.{field}"
        );
    }
    Ok(render_members(&specs, 8))
}
