name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  cargo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo test --locked
  bazel:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ runner.os }}-${{ hashFiles('.bazelversion') }}
      - run: bazel test --lockfile_mode=update //...
      - name: Test the external module
        working-directory: e2e/bzlmod
        run: bazel test --lockfile_mode=update //...
